### ISSUE TITLE
Consider new mascot

### ISSUE THREAD

**Issue by alexmojaki** [BusinessOptics/gryphon#21]
See http://imgur.com/gallery/Xn1rG
Probably not Kiwi + Chipmunk

**Comment by JHSaunders** [comment]
Peregrine Falcon + Cheetah looks like a winner? Can we fine the artist and get CC rights?

**Comment by JHSaunders** [comment]
Recolour it to the grey/green standard.

**Comment by JHSaunders** [comment]
Done and dusted. Check commit log for mascot usage permission or contact @JHSaunders for email trail. Thank you Lauren.
